version: '3'
services:
  express-typescript:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'ryde-backend-developer-test'
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    environment:
      - MONGOOSE_URL=mongodb://mongo:27017/ryde
    command: sh -c 'npm install && npm run dev'
    ports:
      - 8000:8000
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    expose:
      - 27017
